# Generated by Django 3.2.5 on 2021-07-17 16:29

import dataencryption.custom_encrypted_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', dataencryption.custom_encrypted_field.EncryptedTextField()),
            ],
        ),
    ]
